export const ADD_INGREDIENT = 'ADD_INGREDIENTS';
export const REMOVE_INGREDENT = 'REMOVE_INGREDENT';
export const LOAD_INGREDIENT = 'LOAD_INGREDIENT';
export const FETCH_INGREDEITNS_FAIL = 'FETCH_INGREDEITNS_FAIL';

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAILS = 'PURCHASE_FAILS';
export const PURCHASE_LOADING = 'PURCHASE_LOADING';
export const PURCHASE_INIT = 'PURCHASE_INIT';
