export const ADD_INGREDIENT = 'ADD_INGREDIENTS';
export const REMOVE_INGREDENT = 'REMOVE_INGREDENT';
export const LOAD_INGREDIENT = 'LOAD_INGREDIENT';
export const FETCH_INGREDEITNS_FAIL = 'FETCH_INGREDEITNS_FAIL';

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAILS = 'PURCHASE_FAILS';
export const PURCHASE_LOADING = 'PURCHASE_LOADING';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDER_FAILS = 'FETCH_ORDER_FAILS';
export const FETCH_ORDER_START = 'FETCH_ORDER_START';